version: "3.9"
services:
    php:
        container_name: connection-php
        privileged: true
        user: root
        build:
            context: .
            dockerfile: docker/php/dockerfile
        volumes:
            - ./:/var/www/
            - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php/supervisor:/etc/supervisor
            - ./docker/php/cron.d:/etc/cron.d
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - db
            - redis
        networks:
            - connection
    nginx:
        container_name: connection-nginx
        build:
            context: .
            dockerfile: docker/nginx/dockerfile
        ports:
            - "8000:80"
        depends_on:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        networks:
            - connection
    db:
        container_name: connection-mysql
        build:
            context: .
            dockerfile: docker/mysql/dockerfile
        ports:
            - "3319:3306"
        volumes:
            - ./mysql-custom-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: connection
            MYSQL_ROOT_PASSWORD: "L7W729rqIhsZnY0C"
            MYSQL_USER: connection
            MYSQL_PASSWORD: "qy2to1dN"
        networks:
            - connection
    redis:
        build:
            context: docker/redis
            dockerfile: dockerfile
        container_name: connection-redis
        ports:
            - "6388:6379"
        networks:
            - connection
#    swagger-ui:
#        image: swaggerapi/swagger-ui
#        container_name: "connection-swagger-ui"
#        ports:
#            - "8072:8080"
#        volumes:
#            - ./swagger.json:/openapi.json
#        environment:
#            SWAGGER_JSON: /openapi.json
#        networks:
#            - connection
volumes:
    dbdata:
        driver: local

    data-storage:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./storage/app/audio
    data-transcription:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./storage/app/transcription
networks:
    connection:
        driver: bridge
