version: "3.9"
services:
    php:
        container_name: connection-php
        privileged: true
        user: root
        build:
            context: .
            dockerfile: docker/php/dockerfile
        volumes:
            - ./:/var/www/
            - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php/supervisor:/etc/supervisor
            - ./docker/php/cron.d:/etc/cron.d
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            #- ${PUBLIC_DIR_AUDIO}:/var/www/storage/audio
            #- ${PUBLIC_DIR_CALL_INFO}:/var/www/storage/callInfo
        depends_on:
            - db
            - redis
        networks:
            - connection
    nginx:
        container_name: connection-nginx
        build:
            context: .
            dockerfile: docker/nginx/dockerfile
        ports:
            - "8000:80"
        depends_on:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        networks:
            - connection
    db:
        container_name: connection-mysql
        build:
            context: .
            dockerfile: docker/mysql/dockerfile
        ports:
            - "3319:3306"
        volumes:
            - ./mysql-custom-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: connection
            MYSQL_PASSWORD: "qy2to1dN"
        networks:
            - connection
    redis:
        build:
            context: docker/redis
            dockerfile: dockerfile
        container_name: connection-redis
        ports:
            - "6388:6379"
        networks:
            - connection
volumes:
    dbdata:
        driver: local
networks:
    connection:
        driver: bridge
